package git

import (
	"fmt"
	"os"

	"gitup/src/helper"
)

var gitignore = `# This .gitignore file has been generated by the GitUp setup gitignore command.
# It is recommended to manually adjust it to suit your needs.

# Binaries and build outputs
bin/
dist/
build/
*.exe
*.dll
*.so
*.dylib
*.test
*.out

# IDEs and Editors
.vscode/
.idea/
*.swp
*.swo

# Operating System Files
.DS_Store
Thumbs.db
Desktop.ini
`

func WriteGitIgnore(folder string) {
	data := []byte(gitignore)

	err := os.WriteFile(fmt.Sprintf("%s/.gitignore", folder), data, 0644)

	if err != nil {
		helper.LogFail("Failed to write .gitignore: %v", err)
		return
	}

	helper.LogOk("Successfully wrote default .gitignore")
}
